### ISSUE TITLE
AttributeError at /cms/pages/3/edit/preview/ 'WSGIRequest' object has no attribute 'site'

### ISSUE THREAD

**Issue by onsombal** [FlipperPA/peregrine#11]
Draft "Preview" returns the error shown above. When the page is "Published", it displays perfectly.

Thoughts?

**Comment by FlipperPA** [comment]
I think https://github.com/FlipperPA/peregrine/pull/3 may deal with this. Let me take a look today. Thanks for the report!

**Comment by tdxdave** [comment]
I am getting this 3 years later, due to site api changes in Wagtail 2.9.
